import HeroSection from "@/components/HeroSection/HeroSection";
import { Metadata } from "next";
import cover5 from "@/app/assets/cover5.png";
import cover3 from "@/app/assets/cover3.jpg";
import cover2 from "@/app/assets/cover2.jpg";
import AdsBanner from "@/components/share/AdsBanner/AdsBanner";
import Category from "@/components/Category/Category";
import TrendingCollection from "@/components/TrendingCollection/TrendingCollection";
import BestCollection from "@/components/BestCollection/BestCollection";
import FeatureCollection from "@/components/FeatureCollection/FeatureCollection";
import FeatureHighlights from "@/components/FeatureHighlights/FeatureHighlights";
import EmailSubscription from "@/components/EmailSubscription/EmailSubscription";

export const metadata: Metadata = {
  title: "Home | Cloudie Gadgets",
  description: "Generated by create next app",
};
const images = [cover2, cover3, cover2, cover3];
const images2 = [cover2, cover3];
const images3 = [cover3, cover2];
const images5 = [cover5];

export default function Home() {
  return (
    <main className="container mx-auto ">
      <HeroSection />
      <AdsBanner images={images} />
      <Category />
      <TrendingCollection />
      <div className="md:py-4 py-2">
        <AdsBanner images={images2} />
      </div>
      <BestCollection />
      <div className="md:py-4 py-2">
        <AdsBanner images={images3} />
      </div>
      <FeatureCollection />
      <div className="md:pt-4 pt-2 ">
        <AdsBanner images={images5} />
      </div>
      <EmailSubscription />
      <FeatureHighlights />
    </main>
  );
}
