import { ThemeBtn } from "@/components/theme/ThemeBtn";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home | Cloudie Gadgets",
  description: "Generated by create next app",
};

export default function Home() {
  return <div>Special deals CYBER MONDAY SALE</div>;
}
