import HeroSection from "@/components/HeroSection/HeroSection";
import { Metadata } from "next";
import cover5 from "@/app/assets/cover5.png";
import cover3 from "@/app/assets/cover3.jpg";
import cover2 from "@/app/assets/cover2.jpg";
import AdsBanner from "@/components/share/AdsBanner/AdsBanner";
import Category from "@/components/Category/Category";
import TrendingCollection from "@/components/TrendingCollection/TrendingCollection";
import ProductCard from "@/components/share/ProductCard/ProductCard";
import img from "@/app/assets/img3.png";
import BestCollection from "@/components/BestCollection/BestCollection";
import FeatureCollection from "@/components/FeatureCollection/FeatureCollection";
import FeatureHighlights from "@/components/FeatureHighlights/FeatureHighlights";

export const metadata: Metadata = {
  title: "Home | Cloudie Gadgets",
  description: "Generated by create next app",
};
const images = [cover2, cover3, cover2, cover3];
const images2 = [cover2, cover3];
const images3 = [cover3, cover2];
const images4 = [cover2];
const images5 = [cover5];

export default function Home() {
  return (
    <main className="container mx-auto ">
      <HeroSection />
      <AdsBanner images={images} />
      <Category />
      <TrendingCollection />
      <div className="py-4">
        <AdsBanner images={images2} />
      </div>
      <BestCollection />
      <div className="py-4">
        <AdsBanner images={images3} />
      </div>
      <FeatureCollection />
      <div className="py-4 flex justify-center  overflow-hidden mx-4">
        <AdsBanner images={images5} />
      </div>
      <FeatureHighlights />
    </main>
  );
}
